#0x From the 3024_Day color palette


# 0x Default colors

[colors.primary]

background = "#f7f7f7"
foreground = "#494542"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#494542"
cursor = "#a4a1a1"


# 0x Normal colors

[colors.normal]

black   = "#090200"
red     = "#da2c20"
green   = "#00a152"
yellow  = "#fcec02"
blue    = "#00a0e4"
magenta = "#a06994"
cyan    = "#b5e4f4"
white   = "#a4a1a1"


# 0x Bright colors

[colors.bright]

black   = "#5b5754"
red     = "#e8bacf"
green   = "#3a3332"
yellow  = "#494542"
blue    = "#7f7c7b"
magenta = "#d6d4d3"
cyan    = "#ccab53"
white   = "#494542"
