#0x From the Alucard color palette


# 0x Default colors

[colors.primary]

background = "#222330"
foreground = "#cef3ff"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#ffffff"
cursor = "#44475a"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#ff5555"
green   = "#fa0074"
yellow  = "#7f0a1f"
blue    = "#3282ff"
magenta = "#1b3cff"
cyan    = "#0037fc"
white   = "#bbbbbb"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#ff5454"
green   = "#50fa7b"
yellow  = "#f0fa8b"
blue    = "#1200f8"
magenta = "#ff78c5"
cyan    = "#8ae9fc"
white   = "#cef3ff"
