#0x From the Arthur color palette


# 0x Default colors

[colors.primary]

background = "#1c1c1c"
foreground = "#ddeedd"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#e2bbef"
cursor = "#4d4d4d"


# 0x Normal colors

[colors.normal]

black   = "#3d352a"
red     = "#cd5c5c"
green   = "#86af80"
yellow  = "#e8ae5b"
blue    = "#6495ed"
magenta = "#deb887"
cyan    = "#b0c4de"
white   = "#bbaa99"


# 0x Bright colors

[colors.bright]

black   = "#554444"
red     = "#cc5533"
green   = "#88aa22"
yellow  = "#ffa75d"
blue    = "#87ceeb"
magenta = "#996600"
cyan    = "#b0c4de"
white   = "#ddeedd"
