# Name: Atelierdune (dark)
# Author: Chris Kempson

[colors.primary]
background = "#20201d"
foreground = "#a6a28c"

[colors.cursor]
text = "#20201d"
cursor = "#a6a28c"

[colors.normal]
black = "#20201d"
red = "#d73737"
green = "#60ac39"
yellow = "#cfb017"
blue = "#6684e1"
magenta = "#b854d4"
cyan = "#1fad83"
white = "#a6a28c"

[colors.bright]
black = "#7d7a68"
red = "#d73737"
green = "#60ac39"
yellow = "#cfb017"
blue = "#6684e1"
magenta = "#b854d4"
cyan = "#1fad83"
white = "#fefbec"
