# Name: Atelierforest (dark)
# Author: Chris Kempson

[colors.primary]
background = "#1b1918"
foreground = "#a8a19f"

[colors.cursor]
text = "#1b1918"
cursor = "#a8a19f"

[colors.normal]
black = "#1b1918"
red = "#f22c40"
green = "#5ab738"
yellow = "#d5911a"
blue = "#407ee7"
magenta = "#6666ea"
cyan = "#00ad9c"
white = "#a8a19f"

[colors.bright]
black = "#766e6b"
red = "#f22c40"
green = "#5ab738"
yellow = "#d5911a"
blue = "#407ee7"
magenta = "#6666ea"
cyan = "#00ad9c"
white = "#f1efee"
