#0x From the AtomOneLight color palette


# 0x Default colors

[colors.primary]

background = "#f8f8f8"
foreground = "#2a2b33"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#bbbbbb"
cursor = "#ececec"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#de3d35"
green   = "#3e953a"
yellow  = "#d2b67b"
blue    = "#2f5af3"
magenta = "#950095"
cyan    = "#3e953a"
white   = "#bbbbbb"


# 0x Bright colors

[colors.bright]

black   = "#000000"
red     = "#de3d35"
green   = "#3e953a"
yellow  = "#d2b67b"
blue    = "#2f5af3"
magenta = "#a00095"
cyan    = "#3e953a"
white   = "#2a2b33"
