#0x From the ayu_light color palette


# 0x Default colors

[colors.primary]

background = "#fafafa"
foreground = "#5b6673"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#ff6900"
cursor = "#f0ede4"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#ff3333"
green   = "#86b200"
yellow  = "#f19618"
blue    = "#41a6d9"
magenta = "#f07078"
cyan    = "#4cbe99"
white   = "#ffffff"


# 0x Bright colors

[colors.bright]

black   = "#323232"
red     = "#ff6565"
green   = "#b8e532"
yellow  = "#ffc849"
blue    = "#73d7ff"
magenta = "#ffa3aa"
cyan    = "#7ff0cb"
white   = "#5b6673"
