[colors.primary]
background = "#181818"
foreground = "#d8d8d8"

[colors.cursor]
text = "#d8d8d8"
cursor = "#d8d8d8"

[colors.normal]
black = "#181818"
red = "#ab4642"
green = "#a1b56c"
yellow = "#f7ca88"
blue = "#7cafc2"
magenta = "#ba8baf"
cyan = "#86c1b9"
white = "#d8d8d8"

[colors.bright]
black = "#585858"
red = "#ab4642"
green = "#a1b56c"
yellow = "#f7ca88"
blue = "#7cafc2"
magenta = "#ba8baf"
cyan = "#86c1b9"
white = "#f8f8f8"
