#0x From the Belafonte_Night color palette


# 0x Default colors

[colors.primary]

background = "#20111a"
foreground = "#958b83"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#958b83"
cursor = "#45363b"


# 0x Normal colors

[colors.normal]

black   = "#20111a"
red     = "#bd100d"
green   = "#858062"
yellow  = "#e9a448"
blue    = "#416978"
magenta = "#96522b"
cyan    = "#98999c"
white   = "#958b83"


# 0x Bright colors

[colors.bright]

black   = "#5e5252"
red     = "#bd100d"
green   = "#858062"
yellow  = "#e9a448"
blue    = "#416978"
magenta = "#96522b"
cyan    = "#98999c"
white   = "#958b83"
