# Name: Bespin (light)
# Author: Chris Kempson

[colors.primary]
background = "#baae9e"
foreground = "#5e5d5c"

[colors.cursor]
text = "#baae9e"
cursor = "#5e5d5c"

[colors.normal]
black = "#28211c"
red = "#cf6a4c"
green = "#54be0d"
yellow = "#f9ee98"
blue = "#5ea6ea"
magenta = "#9b859d"
cyan = "#afc4db"
white = "#8a8986"

[colors.bright]
black = "#666666"
red = "#cf6a4c"
green = "#54be0d"
yellow = "#f9ee98"
blue = "#5ea6ea"
magenta = "#9b859d"
cyan = "#afc4db"
white = "#baae9e"
