#0x From the Blazer color palette


# 0x Default colors

[colors.primary]

background = "#0d1925"
foreground = "#d9e5f1"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#d9e5f1"
cursor = "#d9e6f2"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#b87979"
green   = "#79b879"
yellow  = "#b8b879"
blue    = "#7979b8"
magenta = "#b879b8"
cyan    = "#79b8b8"
white   = "#d9d9d9"


# 0x Bright colors

[colors.bright]

black   = "#252525"
red     = "#dabdbd"
green   = "#bddabd"
yellow  = "#dadabd"
blue    = "#bdbdda"
magenta = "#dabdda"
cyan    = "#bddada"
white   = "#d9e5f1"
