# Name: Brewer (dark)
# Author: Chris Kempson

[colors.primary]
background = "#0c0d0e"
foreground = "#b7b8b9"

[colors.cursor]
text = "#0c0d0e"
cursor = "#b7b8b9"

[colors.normal]
black = "#0c0d0e"
red = "#e31a1c"
green = "#31a354"
yellow = "#dca060"
blue = "#3182bd"
magenta = "#756bb1"
cyan = "#80b1d3"
white = "#b7b8b9"

[colors.bright]
black = "#737475"
red = "#e31a1c"
green = "#31a354"
yellow = "#dca060"
blue = "#3182bd"
magenta = "#756bb1"
cyan = "#80b1d3"
white = "#fcfdfe"
