#0x From the Brogrammer color palette


# 0x Default colors

[colors.primary]

background = "#131313"
foreground = "#d6dae4"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#b9b9b9"
cursor = "#1f1f1f"


# 0x Normal colors

[colors.normal]

black   = "#1f1f1f"
red     = "#f71118"
green   = "#2cc55d"
yellow  = "#ecb90f"
blue    = "#2a84d2"
magenta = "#4e59b7"
cyan    = "#0f80d5"
white   = "#d6dae4"


# 0x Bright colors

[colors.bright]

black   = "#d6dae4"
red     = "#de342e"
green   = "#1dd260"
yellow  = "#f2bd09"
blue    = "#0f80d5"
magenta = "#524fb9"
cyan    = "#0f7cda"
white   = "#d6dae4"
