#0x From the Chalk color palette


# 0x Default colors

[colors.primary]

background = "#2b2c2e"
foreground = "#d2d8d9"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#708183"
cursor = "#e3e8ed"


# 0x Normal colors

[colors.normal]

black   = "#7c8a8f"
red     = "#b23a51"
green   = "#789a69"
yellow  = "#b9ab4a"
blue    = "#2a7fac"
magenta = "#bc4f5a"
cyan    = "#44a799"
white   = "#d2d8d9"


# 0x Bright colors

[colors.bright]

black   = "#888888"
red     = "#f24840"
green   = "#80c46f"
yellow  = "#ffeb62"
blue    = "#4095ff"
magenta = "#fb5175"
cyan    = "#52ccbd"
white   = "#d2d8d9"
