#0x From the Chalkboard color palette


# 0x Default colors

[colors.primary]

background = "#29262f"
foreground = "#d9e6f2"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#d9e6f2"
cursor = "#073642"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#c37372"
green   = "#72c373"
yellow  = "#c2c372"
blue    = "#7372c3"
magenta = "#c372c2"
cyan    = "#72c2c3"
white   = "#d9d9d9"


# 0x Bright colors

[colors.bright]

black   = "#323232"
red     = "#dbaaaa"
green   = "#aadbaa"
yellow  = "#dadbaa"
blue    = "#aaaadb"
magenta = "#dbaada"
cyan    = "#aadadb"
white   = "#d9e6f2"
