#0x From the Ciapre color palette


# 0x Default colors

[colors.primary]

background = "#181c27"
foreground = "#ada37a"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#91805a"
cursor = "#172539"


# 0x Normal colors

[colors.normal]

black   = "#181818"
red     = "#800009"
green   = "#48513b"
yellow  = "#cc8a3e"
blue    = "#566d8c"
magenta = "#724c7c"
cyan    = "#5b4f4a"
white   = "#ada37e"


# 0x Bright colors

[colors.bright]

black   = "#555555"
red     = "#ab3834"
green   = "#a6a65d"
yellow  = "#dcde7b"
blue    = "#2f97c6"
magenta = "#d33060"
cyan    = "#f3dab1"
white   = "#ada37a"
