#0x From the Cobalt2 color palette


# 0x Default colors

[colors.primary]

background = "#122637"
foreground = "#ffffff"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#f0cb09"
cursor = "#18344f"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#ff0000"
green   = "#37dd21"
yellow  = "#fee409"
blue    = "#1460d2"
magenta = "#ff005d"
cyan    = "#00bbbb"
white   = "#bbbbbb"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#f40d17"
green   = "#3bcf1d"
yellow  = "#ecc809"
blue    = "#5555ff"
magenta = "#ff55ff"
cyan    = "#6ae3f9"
white   = "#ffffff"
