#0x From the Cobalt_Neon color palette


# 0x Default colors

[colors.primary]

background = "#142838"
foreground = "#8ff586"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#c4206f"
cursor = "#084fb0"


# 0x Normal colors

[colors.normal]

black   = "#142630"
red     = "#ff2320"
green   = "#3aa5ff"
yellow  = "#e9e75c"
blue    = "#8ff586"
magenta = "#781aa0"
cyan    = "#8ff586"
white   = "#ba45b1"


# 0x Bright colors

[colors.bright]

black   = "#fff688"
red     = "#d4312e"
green   = "#8ff586"
yellow  = "#e9f06d"
blue    = "#3c7dd2"
magenta = "#8230a7"
cyan    = "#6cbc67"
white   = "#8ff586"
