# Name: Codeschool (dark)
# Author: Chris Kempson

[colors.primary]
background = "#232c31"
foreground = "#9ea7a6"

[colors.cursor]
text = "#232c31"
cursor = "#9ea7a6"

[colors.normal]
black = "#232c31"
red = "#2a5491"
green = "#237986"
yellow = "#a03b1e"
blue = "#484d79"
magenta = "#c59820"
cyan = "#b02f30"
white = "#9ea7a6"

[colors.bright]
black = "#3f4944"
red = "#2a5491"
green = "#237986"
yellow = "#a03b1e"
blue = "#484d79"
magenta = "#c59820"
cyan = "#b02f30"
white = "#b5d8f6"
