# Name: Dawn
# Author: Escapist

[colors.primary]
background = "#181B20"
foreground = "#9B9081"

[colors.cursor]
text = "#181B20"
cursor = "#9B9081"

[colors.normal]
black = "#353535"
red = "#744B40"
green = "#6D6137"
yellow = "#765636"
blue = "#61564B"
magenta = "#6B4A49"
cyan = "#435861"
white = "#B3B3B3"

[colors.bright]
black = "#5F5F5F"
red = "#785850"
green = "#6F6749"
yellow = "#776049"
blue = "#696057"
magenta = "#6F5A59"
cyan = "#525F66"
white = "#CDCDCD"
