#0x From the Desert color palette


# 0x Default colors

[colors.primary]

background = "#333333"
foreground = "#ffffff"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#00ff00"
cursor = "#b5d5ff"


# 0x Normal colors

[colors.normal]

black   = "#4d4d4d"
red     = "#ff2b2b"
green   = "#98fb98"
yellow  = "#f0e68c"
blue    = "#cd853f"
magenta = "#ffdead"
cyan    = "#ffa0a0"
white   = "#f5deb3"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#ff5555"
green   = "#55ff55"
yellow  = "#ffff55"
blue    = "#87ceff"
magenta = "#ff55ff"
cyan    = "#ffd700"
white   = "#ffffff"
