# Name: Red Phoenix
# Author: dkeg

[colors.primary]
background = "#111111"
foreground = "#ffffff"

[colors.cursor]
text = "#111111"
cursor = "#ffffff"

[colors.normal]
black = "#131313"
red = "#2d2d2d"
green = "#4c3a3d"
yellow = "#4e4e4e"
blue = "#6f6f6f"
magenta = "#909090"
cyan = "#aaa998"
white = "#b1b1b1"

[colors.bright]
black = "#d1d1d1"
red = "#d2c3ad"
green = "#df9767"
yellow = "#e1e1e1"
blue = "#ededed"
magenta = "#ed4b19"
cyan = "#f2361e"
white = "#fa390f"
