# Name: Catch Me If You Can
# Author: dkeg

[colors.primary]
background = "#170f0d"
foreground = "#f9f9f9"

[colors.cursor]
text = "#170f0d"
cursor = "#f9f9f9"

[colors.normal]
black = "#130f0c"
red = "#604c38"
green = "#8d7f85"
yellow = "#907256"
blue = "#aa8d70"
magenta = "#b9a38d"
cyan = "#c4bfbf"
white = "#c4ae99"

[colors.bright]
black = "#c69f77"
red = "#cab9a8"
green = "#d5c6b8"
yellow = "#dcd1c7"
blue = "#e0e0e2"
magenta = "#e4dad2"
cyan = "#eae3dc"
white = "#f6f2f0"
