# Name: Canvased Pastel
# Author: dkeg

[colors.primary]
background = "#170f0d"
foreground = "#746c48"

[colors.cursor]
text = "#170f0d"
cursor = "#746c48"

[colors.normal]
black = "#26251c"
red = "#323027"
green = "#3d4339"
yellow = "#443b2c"
blue = "#534d35"
magenta = "#646756"
cyan = "#7b8574"
white = "#837b61"

[colors.bright]
black = "#999f91"
red = "#9b9773"
green = "#b2b08c"
yellow = "#c4bb8c"
blue = "#c4b67a"
magenta = "#cfc995"
cyan = "#d3d4b6"
white = "#d6d3ac"
