#0x From the DotGov color palette


# 0x Default colors

[colors.primary]

background = "#252b35"
foreground = "#eaeaea"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#d9002f"
cursor = "#194080"


# 0x Normal colors

[colors.normal]

black   = "#181818"
red     = "#bf081d"
green   = "#3d9751"
yellow  = "#f6bb33"
blue    = "#16b1df"
magenta = "#772fb0"
cyan    = "#8bd1ed"
white   = "#ffffff"


# 0x Bright colors

[colors.bright]

black   = "#181818"
red     = "#bf081d"
green   = "#3d9751"
yellow  = "#f6bb33"
blue    = "#16b1df"
magenta = "#772fb0"
cyan    = "#8bd1ed"
white   = "#eaeaea"
