#0x From the Dracula color palette


# 0x Default colors

[colors.primary]

background = "#1e1f28"
foreground = "#f8f8f2"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#bbbbbb"
cursor = "#44475a"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f0fa8b"
blue    = "#bd92f8"
magenta = "#ff78c5"
cyan    = "#8ae9fc"
white   = "#bbbbbb"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#ff5454"
green   = "#50fa7b"
yellow  = "#f0fa8b"
blue    = "#bd92f8"
magenta = "#ff78c5"
cyan    = "#8ae9fc"
white   = "#f8f8f2"
