#0x From the Earthsong color palette


# 0x Default colors

[colors.primary]

background = "#282420"
foreground = "#e5c6a8"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#f6f6ec"
cursor = "#111417"


# 0x Normal colors

[colors.normal]

black   = "#111417"
red     = "#c84134"
green   = "#84c44b"
yellow  = "#f4ae2e"
blue    = "#1397b9"
magenta = "#d0623c"
cyan    = "#4f9452"
white   = "#e5c5a9"


# 0x Bright colors

[colors.bright]

black   = "#665e54"
red     = "#ff6459"
green   = "#97e035"
yellow  = "#dfd561"
blue    = "#5ed9ff"
magenta = "#ff9168"
cyan    = "#83ef88"
white   = "#e5c6a8"
