# Name: Embers (dark)
# Author: Chris Kempson

[colors.primary]
background = "#16130f"
foreground = "#a39a90"

[colors.cursor]
text = "#16130f"
cursor = "#a39a90"

[colors.normal]
black = "#16130f"
red = "#826d57"
green = "#57826d"
yellow = "#6d8257"
blue = "#6d5782"
magenta = "#82576d"
cyan = "#576d82"
white = "#a39a90"

[colors.bright]
black = "#5a5047"
red = "#826d57"
green = "#57826d"
yellow = "#6d8257"
blue = "#6d5782"
magenta = "#82576d"
cyan = "#576d82"
white = "#dbd6d1"
