#0x From the FishTank color palette


# 0x Default colors

[colors.primary]

background = "#222436"
foreground = "#eceffd"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#fdcd5e"
cursor = "#fcf6e8"


# 0x Normal colors

[colors.normal]

black   = "#03063c"
red     = "#c60049"
green   = "#abf157"
yellow  = "#fdcd5e"
blue    = "#525fb8"
magenta = "#976f81"
cyan    = "#968662"
white   = "#eceffc"


# 0x Bright colors

[colors.bright]

black   = "#6c5a30"
red     = "#d94a8a"
green   = "#daffa8"
yellow  = "#fee6a8"
blue    = "#b1bdf9"
magenta = "#fda4cc"
cyan    = "#a4bc86"
white   = "#eceffd"
