#0x From the FunForrest color palette


# 0x Default colors

[colors.primary]

background = "#241200"
foreground = "#ddc165"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#e5591c"
cursor = "#e5591c"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#d5252b"
green   = "#909b00"
yellow  = "#bd8a13"
blue    = "#4698a2"
magenta = "#8c4231"
cyan    = "#d98112"
white   = "#ddc165"


# 0x Bright colors

[colors.bright]

black   = "#7e6954"
red     = "#e4591b"
green   = "#bfc659"
yellow  = "#ffca1b"
blue    = "#7cc9ce"
magenta = "#d16349"
cyan    = "#e6a96b"
white   = "#ddc165"
