#0x From the Galaxy color palette


# 0x Default colors

[colors.primary]

background = "#1c2836"
foreground = "#ffffff"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#bbbbbb"
cursor = "#b4d5ff"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#f9555f"
green   = "#20af89"
yellow  = "#fdf029"
blue    = "#589cf5"
magenta = "#934d95"
cyan    = "#1e9ee6"
white   = "#bbbbbb"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#fa8b8e"
green   = "#34bb99"
yellow  = "#ffff55"
blue    = "#589cf5"
magenta = "#e75598"
cyan    = "#3978bb"
white   = "#ffffff"
