#0x From the Grape color palette


# 0x Default colors

[colors.primary]

background = "#161423"
foreground = "#9e9ea0"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#a188f7"
cursor = "#483d70"


# 0x Normal colors

[colors.normal]

black   = "#2d283e"
red     = "#ec2160"
green   = "#1fa91b"
yellow  = "#8ddc1f"
blue    = "#487cf4"
magenta = "#8c35c8"
cyan    = "#3added"
white   = "#9e9ea0"


# 0x Bright colors

[colors.bright]

black   = "#58506a"
red     = "#f0719a"
green   = "#52a95d"
yellow  = "#b2dc87"
blue    = "#a9bbeb"
magenta = "#ac81c1"
cyan    = "#9ce3ea"
white   = "#9e9ea0"
