#0x From the gruvbox_light color palette


# 0x Default colors

[colors.primary]

background = "#fbf1c7"
foreground = "#3c3836"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#928374"
cursor = "#928374"


# 0x Normal colors

[colors.normal]

black   = "#fbf1c7"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#7c6f64"


# 0x Bright colors

[colors.bright]

black   = "#282828"
red     = "#9d0006"
green   = "#79740e"
yellow  = "#b57614"
blue    = "#076678"
magenta = "#8f3f71"
cyan    = "#427b58"
white   = "#3c3836"
