#0x From the gruvbox_dark color palette


# 0x Default colors

[colors.primary]

background = "#282828"
foreground = "#ebdbb2"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#928374"
cursor = "#3c3836"


# 0x Normal colors

[colors.normal]

black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"


# 0x Bright colors

[colors.bright]

black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2d"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"
