# Name: Nature Suede
# Author: Gslob

[colors.primary]
background = "#170f0d"
foreground = "#746c48"

[colors.cursor]
text = "#170f0d"
cursor = "#746c48"

[colors.normal]
black = "#392925"
red = "#98724c"
green = "#908f32"
yellow = "#aa964c"
blue = "#7b854e"
magenta = "#6b5644"
cyan = "#5c5142"
white = "#c8b55b"

[colors.bright]
black = "#544b2e"
red = "#af652f"
green = "#c3c13d"
yellow = "#c8b55b"
blue = "#70a16c"
magenta = "#98724c"
cyan = "#778725"
white = "#e4dc8c"
