# Name: Light White
# Author: Gutterslob

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#808080"
red = "#c48980"
green = "#8da862"
yellow = "#b29b7a"
blue = "#809bc4"
magenta = "#aa88b2"
cyan = "#82adad"
white = "#bfbfbf"

[colors.bright]
black = "#9c9c9c"
red = "#a15048"
green = "#4b7508"
yellow = "#916f27"
blue = "#567cb0"
magenta = "#964e8f"
cyan = "#4e848a"
white = "#9c9c9c"
