#0x From the Harper color palette


# 0x Default colors

[colors.primary]

background = "#000000"
foreground = "#a7a39c"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#a7a39c"
cursor = "#5a5753"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#f7b63e"
green   = "#7fb5e1"
yellow  = "#d6da24"
blue    = "#489d48"
magenta = "#b295c5"
cyan    = "#f4bed6"
white   = "#a7a39c"


# 0x Bright colors

[colors.bright]

black   = "#716d69"
red     = "#f7b63e"
green   = "#7fb5e1"
yellow  = "#d6da24"
blue    = "#489d48"
magenta = "#b295c5"
cyan    = "#f4bed6"
white   = "#a7a39c"
