#0x From the Homebrew color palette


# 0x Default colors

[colors.primary]

background = "#000000"
foreground = "#00ff00"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#23ff18"
cursor = "#083905"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#990000"
green   = "#00a600"
yellow  = "#999900"
blue    = "#0000b2"
magenta = "#b200b2"
cyan    = "#00a6b2"
white   = "#bebebe"


# 0x Bright colors

[colors.bright]

black   = "#666666"
red     = "#e50000"
green   = "#00d900"
yellow  = "#e5e500"
blue    = "#0000ff"
magenta = "#e500e5"
cyan    = "#00e5e5"
white   = "#00ff00"
