# Name: hund
# Author: hund

[colors.primary]
background = "#161616"
foreground = "#FFFFFF"

[colors.cursor]
text = "#161616"
cursor = "#FFFFFF"

[colors.normal]
black = "#222222"
red = "#E84F4F"
green = "#B7CE42"
yellow = "#FEA63C"
blue = "#66AABB"
magenta = "#B7416E"
cyan = "#6D878D"
white = "#DDDDDD"

[colors.bright]
black = "#666666"
red = "#D23D3D"
green = "#BDE077"
yellow = "#FFE863"
blue = "#AACCBB"
magenta = "#E16A98"
cyan = "#42717B"
white = "#CCCCCC"
