# Name: Iiamblack
# Author: iiamblack

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#393939"
red = "#da4939"
green = "#519f50"
yellow = "#cc7833"
blue = "#6d9cbe"
magenta = "#9f5079"
cyan = "#435d75"
white = "#dddddd"

[colors.bright]
black = "#474747"
red = "#ff6c5c"
green = "#a5c261"
yellow = "#bc9458"
blue = "#d0d0ff"
magenta = "#a761c2"
cyan = "#6e98a4"
white = "#dddddd"
