#0x From the IR_Black color palette


# 0x Default colors

[colors.primary]

background = "#000000"
foreground = "#f1f1f1"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#7f7f7f"
cursor = "#b4d5ff"


# 0x Normal colors

[colors.normal]

black   = "#4f4f4f"
red     = "#fa6c5f"
green   = "#a8fe60"
yellow  = "#fffeb6"
blue    = "#96cafd"
magenta = "#fa72fc"
cyan    = "#c6c4fd"
white   = "#eeedee"


# 0x Bright colors

[colors.bright]

black   = "#7b7b7b"
red     = "#fcb6af"
green   = "#ceffab"
yellow  = "#fffecc"
blue    = "#b5dcfe"
magenta = "#fb9bfe"
cyan    = "#dfdffd"
white   = "#f1f1f1"
