#0x From the Japanesque color palette


# 0x Default colors

[colors.primary]

background = "#1d1d1d"
foreground = "#f7f6ec"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#eccf4f"
cursor = "#165776"


# 0x Normal colors

[colors.normal]

black   = "#343835"
red     = "#ce3e60"
green   = "#7bb75b"
yellow  = "#e8b32a"
blue    = "#4c99d3"
magenta = "#a57fc4"
cyan    = "#389aac"
white   = "#f9faf6"


# 0x Bright colors

[colors.bright]

black   = "#585a58"
red     = "#d18ea6"
green   = "#767e2b"
yellow  = "#77592e"
blue    = "#135879"
magenta = "#5f4190"
cyan    = "#76bbca"
white   = "#f7f6ec"
