# Name: Jason Wryan
# Author: 

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#222222"
red = "#9e5641"
green = "#6c7e55"
yellow = "#caaf2b"
blue = "#4c8ea1"
magenta = "#956d9d"
cyan = "#7c9aa6"
white = "#909090"

[colors.bright]
black = "#454545"
red = "#cc896d"
green = "#7db37d"
yellow = "#bfb556"
blue = "#6bc1d0"
magenta = "#c18fcb"
cyan = "#8fadbf"
white = "#ffffff"
