#0x From the JetBrains_Darcula color palette


# 0x Default colors

[colors.primary]

background = "#202020"
foreground = "#adadad"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#ffffff"
cursor = "#1a3272"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#fa5355"
green   = "#126e00"
yellow  = "#c2c300"
blue    = "#4581eb"
magenta = "#fa54ff"
cyan    = "#33c2c1"
white   = "#adadad"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#fb7172"
green   = "#67ff4f"
yellow  = "#ffff00"
blue    = "#6d9df1"
magenta = "#fb82ff"
cyan    = "#60d3d1"
white   = "#adadad"
