#0x From the Kibble color palette


# 0x Default colors

[colors.primary]

background = "#0e100a"
foreground = "#f7f7f7"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#9fda9c"
cursor = "#9ba686"


# 0x Normal colors

[colors.normal]

black   = "#4d4d4d"
red     = "#c70031"
green   = "#29cf13"
yellow  = "#d8e30e"
blue    = "#3449d1"
magenta = "#8400ff"
cyan    = "#0798ab"
white   = "#e2d1e3"


# 0x Bright colors

[colors.bright]

black   = "#5a5a5a"
red     = "#f01578"
green   = "#6ce05c"
yellow  = "#f3f79e"
blue    = "#97a4f7"
magenta = "#c495f0"
cyan    = "#68f2e0"
white   = "#f7f7f7"
