#0x From the Lavandula color palette


# 0x Default colors

[colors.primary]

background = "#050014"
foreground = "#736d7c"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#8b91fa"
cursor = "#36323b"


# 0x Normal colors

[colors.normal]

black   = "#230045"
red     = "#7c1525"
green   = "#337e6f"
yellow  = "#7f6f49"
blue    = "#4f4a7f"
magenta = "#593f7e"
cyan    = "#57767f"
white   = "#736d7c"


# 0x Bright colors

[colors.bright]

black   = "#362c45"
red     = "#df5066"
green   = "#52e0c4"
yellow  = "#e0c286"
blue    = "#8e86df"
magenta = "#a675df"
cyan    = "#9ad3df"
white   = "#736d7c"
