#0x From the Man_Page color palette


# 0x Default colors

[colors.primary]

background = "#fef49c"
foreground = "#000000"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#7f7f7f"
cursor = "#a4c9cd"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#cc0000"
green   = "#00a600"
yellow  = "#999900"
blue    = "#0000b2"
magenta = "#b200b2"
cyan    = "#00a6b2"
white   = "#cccccc"


# 0x Bright colors

[colors.bright]

black   = "#666666"
red     = "#e50000"
green   = "#00d900"
yellow  = "#e5e500"
blue    = "#0000ff"
magenta = "#e500e5"
cyan    = "#00e5e5"
white   = "#000000"
