# Name: Marrakesh (dark)
# Author: Chris Kempson

[colors.primary]
background = "#201602"
foreground = "#948e48"

[colors.cursor]
text = "#201602"
cursor = "#948e48"

[colors.normal]
black = "#201602"
red = "#c35359"
green = "#18974e"
yellow = "#a88339"
blue = "#477ca1"
magenta = "#8868b3"
cyan = "#75a738"
white = "#948e48"

[colors.bright]
black = "#6c6823"
red = "#c35359"
green = "#18974e"
yellow = "#a88339"
blue = "#477ca1"
magenta = "#8868b3"
cyan = "#75a738"
white = "#faf0a5"
