#0x From the Material color palette


# 0x Default colors

[colors.primary]

background = "#eaeaea"
foreground = "#222221"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#16aec9"
cursor = "#c1c1c1"


# 0x Normal colors

[colors.normal]

black   = "#212121"
red     = "#b7141e"
green   = "#457b23"
yellow  = "#f5971d"
blue    = "#134eb2"
magenta = "#550087"
cyan    = "#0e707c"
white   = "#eeeeee"


# 0x Bright colors

[colors.bright]

black   = "#424242"
red     = "#e83a3f"
green   = "#7aba39"
yellow  = "#fee92e"
blue    = "#53a4f3"
magenta = "#a94dbb"
cyan    = "#26bad1"
white   = "#222221"
