#0x From the Mathias color palette


# 0x Default colors

[colors.primary]

background = "#000000"
foreground = "#bbbbbb"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#bbbbbb"
cursor = "#545454"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#e52222"
green   = "#a6e32d"
yellow  = "#fc951e"
blue    = "#c48dff"
magenta = "#fa2573"
cyan    = "#67d9f0"
white   = "#f2f2f2"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#ff5555"
green   = "#55ff55"
yellow  = "#ffff55"
blue    = "#5555ff"
magenta = "#ff55ff"
cyan    = "#55ffff"
white   = "#bbbbbb"
