#0x From the Medallion color palette


# 0x Default colors

[colors.primary]

background = "#1d1808"
foreground = "#cac296"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#d3b92f"
cursor = "#616cab"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#b54c00"
green   = "#7c8a16"
yellow  = "#d2bd25"
blue    = "#606baf"
magenta = "#8b5990"
cyan    = "#906b25"
white   = "#c9c199"


# 0x Bright colors

[colors.bright]

black   = "#5e5118"
red     = "#ff9148"
green   = "#b1c93a"
yellow  = "#ffe449"
blue    = "#abb8ff"
magenta = "#fe9fff"
cyan    = "#ffbb51"
white   = "#cac296"
