# Name: Mocha (light)
# Author: Chris Kempson

[colors.primary]
background = "#f5eeeb"
foreground = "#645240"

[colors.cursor]
text = "#f5eeeb"
cursor = "#645240"

[colors.normal]
black = "#3b3228"
red = "#cb6077"
green = "#beb55b"
yellow = "#f4bc87"
blue = "#8ab3b5"
magenta = "#a89bb9"
cyan = "#7bbda4"
white = "#d0c8c6"

[colors.bright]
black = "#7e705a"
red = "#cb6077"
green = "#beb55b"
yellow = "#f4bc87"
blue = "#8ab3b5"
magenta = "#a89bb9"
cyan = "#7bbda4"
white = "#f5eeeb"
