#0x From the Molokai color palette


# 0x Default colors

[colors.primary]

background = "#121212"
foreground = "#bbbbbb"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#bbbbbb"
cursor = "#b4d5ff"


# 0x Normal colors

[colors.normal]

black   = "#121212"
red     = "#fa2573"
green   = "#97e123"
yellow  = "#dfd460"
blue    = "#0f7fcf"
magenta = "#8700ff"
cyan    = "#42a7cf"
white   = "#bbbbbb"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#f5669c"
green   = "#b0e05e"
yellow  = "#fef26c"
blue    = "#00afff"
magenta = "#af87ff"
cyan    = "#50cdfe"
white   = "#bbbbbb"
