#0x From the MonaLisa color palette


# 0x Default colors

[colors.primary]

background = "#110b0d"
foreground = "#f6d56a"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#c36c32"
cursor = "#f6d56a"


# 0x Normal colors

[colors.normal]

black   = "#341a0d"
red     = "#9b281b"
green   = "#626132"
yellow  = "#c26e27"
blue    = "#515b5c"
magenta = "#9b1d29"
cyan    = "#588056"
white   = "#f6d75c"


# 0x Bright colors

[colors.bright]

black   = "#874227"
red     = "#ff4230"
green   = "#b3b163"
yellow  = "#ff9565"
blue    = "#9eb2b3"
magenta = "#ff5b6a"
cyan    = "#89cc8e"
white   = "#f6d56a"
