# Name: Monokai (light)
# Author: Chris Kempson

[colors.primary]
background = "#f9f8f5"
foreground = "#49483e"

[colors.cursor]
text = "#f9f8f5"
cursor = "#49483e"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
