# Name: Pastel White
# Author: Muzieca

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#646e5b"
red = "#db7464"
green = "#a7e160"
yellow = "#dbd560"
blue = "#69b2d6"
magenta = "#a073d6"
cyan = "#69e1d3"
white = "#9ea894"

[colors.bright]
black = "#88927e"
red = "#dba08f"
green = "#bde18b"
yellow = "#dbda8b"
blue = "#95a9d6"
magenta = "#b59fd6"
cyan = "#95e1d2"
white = "#c9d0c2"
