#0x From the N0tch2k color palette


# 0x Default colors

[colors.primary]

background = "#222222"
foreground = "#a0a0a0"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#a99075"
cursor = "#4d4d4d"


# 0x Normal colors

[colors.normal]

black   = "#383838"
red     = "#a95551"
green   = "#666666"
yellow  = "#a98051"
blue    = "#657d3e"
magenta = "#767676"
cyan    = "#c9c9c9"
white   = "#d0b8a3"


# 0x Bright colors

[colors.bright]

black   = "#474747"
red     = "#a97775"
green   = "#8c8c8c"
yellow  = "#a99175"
blue    = "#98bd5e"
magenta = "#a3a3a3"
cyan    = "#dcdcdc"
white   = "#a0a0a0"
