# Name: Navy and Ivory
# Author: hal

[colors.primary]
background = "#021b21"
foreground = "#e8dfd6"

[colors.cursor]
text = "#021b21"
cursor = "#e8dfd6"

[colors.normal]
black = "#032c36"
red = "#c2454e"
green = "#7cbf9e"
yellow = "#8a7a63"
blue = "#2e3340"
magenta = "#ff5879"
cyan = "#44b5b1"
white = "#f2f1b9"

[colors.bright]
black = "#065f73"
red = "#ef5847"
green = "#a2d9b1"
yellow = "#beb090"
blue = "#61778d"
magenta = "#ff99a1"
cyan = "#9ed9d8"
white = "#f6f6c9"
