#0x From the Neopolitan color palette


# 0x Default colors

[colors.primary]

background = "#271f19"
foreground = "#ffffff"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#ffffff"
cursor = "#253b76"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#800000"
green   = "#61ce3c"
yellow  = "#fbde2d"
blue    = "#253b76"
magenta = "#ff0080"
cyan    = "#8da6ce"
white   = "#f8f8f8"


# 0x Bright colors

[colors.bright]

black   = "#000000"
red     = "#800000"
green   = "#61ce3c"
yellow  = "#fbde2d"
blue    = "#253b76"
magenta = "#ff0080"
cyan    = "#8da6ce"
white   = "#ffffff"
