#0x From the Neutron color palette


# 0x Default colors

[colors.primary]

background = "#1b1d22"
foreground = "#e6e8ee"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#f6f6ec"
cursor = "#2e353d"


# 0x Normal colors

[colors.normal]

black   = "#22252b"
red     = "#b53f36"
green   = "#5ab977"
yellow  = "#ddb566"
blue    = "#6a7b92"
magenta = "#a3799d"
cyan    = "#3f93a8"
white   = "#e6e8ee"


# 0x Bright colors

[colors.bright]

black   = "#22252b"
red     = "#b53f36"
green   = "#5ab977"
yellow  = "#ddb566"
blue    = "#6a7b92"
magenta = "#a3799d"
cyan    = "#3f93a8"
white   = "#e6e8ee"
