#0x From the NightLion_v2 color palette


# 0x Default colors

[colors.primary]

background = "#171717"
foreground = "#bbbbbb"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#bbbbbb"
cursor = "#b4d5ff"


# 0x Normal colors

[colors.normal]

black   = "#4c4c4c"
red     = "#bb0000"
green   = "#03f622"
yellow  = "#f2f067"
blue    = "#63d0f0"
magenta = "#ce6fda"
cyan    = "#00d9df"
white   = "#bbbbbb"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#ff5555"
green   = "#7df61c"
yellow  = "#ffff55"
blue    = "#62cae7"
magenta = "#ff9af5"
cyan    = "#00ccd7"
white   = "#bbbbbb"
