#0x From the Novel color palette


# 0x Default colors

[colors.primary]

background = "#dfdbc3"
foreground = "#3b2322"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#73635a"
cursor = "#a4a390"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#cc0000"
green   = "#009600"
yellow  = "#d06b00"
blue    = "#0000cc"
magenta = "#cc00cc"
cyan    = "#0087cc"
white   = "#cccccc"


# 0x Bright colors

[colors.bright]

black   = "#7f7f7f"
red     = "#cc0000"
green   = "#009600"
yellow  = "#d06b00"
blue    = "#0000cc"
magenta = "#cc00cc"
cyan    = "#0086cb"
white   = "#3b2322"
