# Name: Nucolors
# Author: 

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#393939"
red = "#ff9f95"
green = "#e2ffc7"
yellow = "#ffffb9"
blue = "#a8ceea"
magenta = "#e2b5cc"
cyan = "#c2efff"
white = "#dddddd"

[colors.bright]
black = "#474747"
red = "#ff8d80"
green = "#dbffb3"
yellow = "#ffbe64"
blue = "#7eb6ff"
magenta = "#e296ff"
cyan = "#9ce9ff"
white = "#dddddd"
