# Name: Numix Darkest
# Author: 

[colors.primary]
background = "#282828"
foreground = "#a2a2a2"

[colors.cursor]
text = "#282828"
cursor = "#a2a2a2"

[colors.normal]
black = "#555555"
red = "#9c3528"
green = "#61bc3b"
yellow = "#f3b43a"
blue = "#0d68a8"
magenta = "#744560"
cyan = "#288e9c"
white = "#a2a2a2"

[colors.bright]
black = "#888888"
red = "#d64937"
green = "#86df5d"
yellow = "#fdd75a"
blue = "#0f75bd"
magenta = "#9e5e83"
cyan = "#37c3d6"
white = "#f9f9f9"
