# Name: Ocean (light)
# Author: Chris Kempson

[colors.primary]
background = "#eff1f5"
foreground = "#4f5b66"

[colors.cursor]
text = "#eff1f5"
cursor = "#4f5b66"

[colors.normal]
black = "#2b303b"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#8fa1b3"
magenta = "#b48ead"
cyan = "#96b5b4"
white = "#c0c5ce"

[colors.bright]
black = "#65737e"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#8fa1b3"
magenta = "#b48ead"
cyan = "#96b5b4"
white = "#eff1f5"
