[colors.cursor]
text = "#fefff2"
cursor = "#ffb86c"

[colors.selection]
text = "#e6e6e6"
background = "#555555"

[colors.primary]
background = "#292a2b"
foreground = "#e6e6e6"

[colors.normal]
black = "#292a2b"
red = "#ff2c6d"
green = "#19f9d8"
yellow = "#ffb86c"
blue = "#45a9f9"
magenta = "#ff75b5"
cyan = "#6fc1ff"
white = "#e6e6e6"

[colors.bright]
black = "#555555"
red = "#ff2c6d"
green = "#19f9d8"
yellow = "#ffcc95"
blue = "#6fc1ff"
magenta = "#ff9ac1"
cyan = "#6fc1ff"
white = "#ffffff"
