# Name: Paraiso (light)
# Author: Chris Kempson

[colors.primary]
background = "#e7e9db"
foreground = "#4f424c"

[colors.cursor]
text = "#e7e9db"
cursor = "#4f424c"

[colors.normal]
black = "#2f1e2e"
red = "#ef6155"
green = "#48b685"
yellow = "#fec418"
blue = "#06b6ef"
magenta = "#815ba4"
cyan = "#5bc4bf"
white = "#a39e9b"

[colors.bright]
black = "#776e71"
red = "#ef6155"
green = "#48b685"
yellow = "#fec418"
blue = "#06b6ef"
magenta = "#815ba4"
cyan = "#5bc4bf"
white = "#e7e9db"
