# Name: Paraiso (dark)
# Author: Chris Kempson

[colors.primary]
background = "#2f1e2e"
foreground = "#a39e9b"

[colors.cursor]
text = "#2f1e2e"
cursor = "#a39e9b"

[colors.normal]
black = "#2f1e2e"
red = "#ef6155"
green = "#48b685"
yellow = "#fec418"
blue = "#06b6ef"
magenta = "#815ba4"
cyan = "#5bc4bf"
white = "#a39e9b"

[colors.bright]
black = "#776e71"
red = "#ef6155"
green = "#48b685"
yellow = "#fec418"
blue = "#06b6ef"
magenta = "#815ba4"
cyan = "#5bc4bf"
white = "#e7e9db"
