# Name: Parker Brothers
# Author: 

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#322a2c"
red = "#79220e"
green = "#344b1b"
yellow = "#b45b00"
blue = "#434045"
magenta = "#5c1e25"
cyan = "#394745"
white = "#ae8842"

[colors.bright]
black = "#46423b"
red = "#aa261f"
green = "#76550f"
yellow = "#b57f02"
blue = "#908862"
magenta = "#624a35"
cyan = "#393e38"
white = "#a59058"
