#0x From the PaulMillr color palette


# 0x Default colors

[colors.primary]

background = "#000000"
foreground = "#f1f1f1"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#4c4c4c"
cursor = "#414141"


# 0x Normal colors

[colors.normal]

black   = "#2a2a2a"
red     = "#ff0000"
green   = "#78ff0e"
yellow  = "#e6be00"
blue    = "#396ad6"
magenta = "#b348bd"
cyan    = "#66ccff"
white   = "#bababa"


# 0x Bright colors

[colors.bright]

black   = "#666666"
red     = "#ff007f"
green   = "#66ff66"
yellow  = "#f3d64d"
blue    = "#7099ec"
magenta = "#da66e5"
cyan    = "#79def1"
white   = "#f1f1f1"
