#0x From the PencilLight color palette


# 0x Default colors

[colors.primary]

background = "#f0f0f0"
foreground = "#414141"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#20bafb"
cursor = "#b6d6fc"


# 0x Normal colors

[colors.normal]

black   = "#202020"
red     = "#c30670"
green   = "#10a778"
yellow  = "#a79c14"
blue    = "#008ec4"
magenta = "#523b78"
cyan    = "#20a4b9"
white   = "#d9d9d9"


# 0x Bright colors

[colors.bright]

black   = "#414141"
red     = "#fb0079"
green   = "#5ed6ae"
yellow  = "#f3e42f"
blue    = "#20bafb"
magenta = "#6854de"
cyan    = "#4fb8cc"
white   = "#414141"
