#0x From the Pnevma color palette


# 0x Default colors

[colors.primary]

background = "#1c1c1c"
foreground = "#d0d0d0"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#e3c8ae"
cursor = "#4d4d4d"


# 0x Normal colors

[colors.normal]

black   = "#2f2e2d"
red     = "#a36666"
green   = "#90a57d"
yellow  = "#d7af87"
blue    = "#7fa5bd"
magenta = "#c79ec4"
cyan    = "#8adbb4"
white   = "#d0d0d0"


# 0x Bright colors

[colors.bright]

black   = "#4a4845"
red     = "#d78787"
green   = "#afbea2"
yellow  = "#e4c9af"
blue    = "#a1bdce"
magenta = "#d7beda"
cyan    = "#b1e7dd"
white   = "#d0d0d0"
