# Name: Pretty and Pastel
# Author: IWAFU

[colors.primary]
background = "#151515"
foreground = "#888888"

[colors.cursor]
text = "#151515"
cursor = "#888888"

[colors.normal]
black = "#292929"
red = "#CF6A4C"
green = "#19CB00"
yellow = "#FAD07A"
blue = "#8197BF"
magenta = "#8787AF"
cyan = "#668799"
white = "#888888"

[colors.bright]
black = "#525252"
red = "#FF9D80"
green = "#23FD00"
yellow = "#FFEFBF"
blue = "#ACCAFF"
magenta = "#C4C4FF"
cyan = "#80BFAF"
white = "#E8E8D3"
