#0x From the Pro color palette


# 0x Default colors

[colors.primary]

background = "#000000"
foreground = "#f2f2f2"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#4d4d4d"
cursor = "#414141"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#990000"
green   = "#00a600"
yellow  = "#999900"
blue    = "#1f08db"
magenta = "#b200b2"
cyan    = "#00a6b2"
white   = "#bfbfbf"


# 0x Bright colors

[colors.bright]

black   = "#666666"
red     = "#e50000"
green   = "#00d900"
yellow  = "#e5e500"
blue    = "#0000ff"
magenta = "#e500e5"
cyan    = "#00e5e5"
white   = "#f2f2f2"
