#0x From the Relaxed_Afterglow color palette


# 0x Default colors

[colors.primary]

background = "#353a44"
foreground = "#d9d9d9"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#d9d9d9"
cursor = "#6a7984"


# 0x Normal colors

[colors.normal]

black   = "#151515"
red     = "#bc5653"
green   = "#909d63"
yellow  = "#ebc17a"
blue    = "#6a8799"
magenta = "#b06698"
cyan    = "#c9dfff"
white   = "#d9d9d9"


# 0x Bright colors

[colors.bright]

black   = "#636363"
red     = "#bc5653"
green   = "#a0ac77"
yellow  = "#ebc17a"
blue    = "#7eaac7"
magenta = "#b06698"
cyan    = "#acbbd0"
white   = "#d9d9d9"
