#0x From the Renault_Style_Light color palette


# 0x Default colors

[colors.primary]

background = "#3a3a3a"
foreground = "#e9cb7b"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#7f7f7f"
cursor = "#958553"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#da4839"
green   = "#509f50"
yellow  = "#ffd249"
blue    = "#46657d"
magenta = "#cfcfff"
cyan    = "#87c1f1"
white   = "#ffffff"


# 0x Bright colors

[colors.bright]

black   = "#323232"
red     = "#ff7b6a"
green   = "#83d082"
yellow  = "#ffff7b"
blue    = "#9fcef0"
magenta = "#ffffff"
cyan    = "#a4d4f8"
white   = "#e9cb7b"
