# Name: SOS
# Author: Rooster

[colors.primary]
background = "#373b43"
foreground = "#78796f"

[colors.cursor]
text = "#373b43"
cursor = "#78796f"

[colors.normal]
black = "#373b43"
red = "#fdcd39"
green = "#fbfd59"
yellow = "#deac40"
blue = "#afb171"
magenta = "#b387e7"
cyan = "#63e860"
white = "#efdecb"

[colors.bright]
black = "#373b43"
red = "#fdcd39"
green = "#fbfd59"
yellow = "#deac40"
blue = "#afb171"
magenta = "#b387e7"
cyan = "#63e860"
white = "#efdecb"
