# Name: s3r0 modified
# Author: earsplit

[colors.primary]
background = "#1F1F1F"
foreground = "#C0B18B"

[colors.cursor]
text = "#1F1F1F"
cursor = "#C0B18B"

[colors.normal]
black = "#4A3637"
red = "#D17B49"
green = "#7B8748"
yellow = "#AF865A"
blue = "#535C5C"
magenta = "#775759"
cyan = "#6D715E"
white = "#C0B18B"

[colors.bright]
black = "#4A3637"
red = "#D17B49"
green = "#7B8748"
yellow = "#AF865A"
blue = "#535C5C"
magenta = "#775759"
cyan = "#6D715E"
white = "#C0B18B"
