#0x From the SeaShells color palette


# 0x Default colors

[colors.primary]

background = "#08131a"
foreground = "#deb88d"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#fba02f"
cursor = "#1e4862"


# 0x Normal colors

[colors.normal]

black   = "#17384c"
red     = "#d05023"
green   = "#027b9b"
yellow  = "#fba02f"
blue    = "#1d4850"
magenta = "#68d3f0"
cyan    = "#50a3b5"
white   = "#deb88d"


# 0x Bright colors

[colors.bright]

black   = "#424b52"
red     = "#d38677"
green   = "#618c98"
yellow  = "#fdd29e"
blue    = "#1abcdd"
magenta = "#bbe3ee"
cyan    = "#86abb3"
white   = "#deb88d"
