#0x From the Seti color palette


# 0x Default colors

[colors.primary]

background = "#111213"
foreground = "#cacecd"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#e2be21"
cursor = "#303233"


# 0x Normal colors

[colors.normal]

black   = "#323232"
red     = "#c22832"
green   = "#8ec43d"
yellow  = "#e0c64f"
blue    = "#43a5d5"
magenta = "#8b57b5"
cyan    = "#8ec43d"
white   = "#eeeeee"


# 0x Bright colors

[colors.bright]

black   = "#323232"
red     = "#c22832"
green   = "#8ec43d"
yellow  = "#e0c64f"
blue    = "#43a5d5"
magenta = "#8b57b5"
cyan    = "#8ec43d"
white   = "#cacecd"
