[colors.primary]
background = "#1E1E3F"
foreground = "#FFFFFF"

[colors.cursor]
text = "#1E1E3F"
cursor = "#FAD000"

[colors.normal]
black = "#000000"
red = "#D52822"
green = "#3DB72A"
yellow = "#FAD000"
blue = "#6943FF"
magenta = "#FF628C"
cyan = "#9EFFFF"
white = "#DBDBE0"

[colors.bright]
black = "#5C5C61"
red = "#FF000D"
green = "#3AD900"
yellow = "#FAD000"
blue = "#6943FF"
magenta = "#FF628C"
cyan = "#9EFFFF"
white = "#FFFFFF"
