#0x From the Shaman color palette


# 0x Default colors

[colors.primary]

background = "#001014"
foreground = "#405555"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#49fcd5"
cursor = "#415554"


# 0x Normal colors

[colors.normal]

black   = "#012026"
red     = "#b12f2c"
green   = "#00a940"
yellow  = "#5d8aa9"
blue    = "#449985"
magenta = "#00599c"
cyan    = "#5c7e19"
white   = "#405554"


# 0x Bright colors

[colors.bright]

black   = "#374350"
red     = "#ff4242"
green   = "#2aea5e"
yellow  = "#8dd3fd"
blue    = "#61d4b9"
magenta = "#1298ff"
cyan    = "#98cf28"
white   = "#405555"
