# Name: Shapeshifter (light)
# Author: Chris Kempson

[colors.primary]
background = "#f9f9f9"
foreground = "#102015"

[colors.cursor]
text = "#f9f9f9"
cursor = "#102015"

[colors.normal]
black = "#000000"
red = "#e92f2f"
green = "#0ed839"
yellow = "#dddd13"
blue = "#3b48e3"
magenta = "#f996e2"
cyan = "#23edda"
white = "#ababab"

[colors.bright]
black = "#343434"
red = "#e92f2f"
green = "#0ed839"
yellow = "#dddd13"
blue = "#3b48e3"
magenta = "#f996e2"
cyan = "#23edda"
white = "#f9f9f9"
