# Name: Simple Rainbow
# Author: 

[colors.primary]
background = "#575757"
foreground = "#dcdccc"

[colors.cursor]
text = "#575757"
cursor = "#dcdccc"

[colors.normal]
black = "#666666"
red = "#ff8278"
green = "#bde077"
yellow = "#eadc84"
blue = "#77bee0"
magenta = "#dd91f3"
cyan = "#ffc178"
white = "#dddddd"

[colors.bright]
black = "#888888"
red = "#ff8278"
green = "#bde077"
yellow = "#eadc84"
blue = "#77bee0"
magenta = "#dd91f3"
cyan = "#ffc178"
white = "#cccccc"
