#0x From the Slate color palette


# 0x Default colors

[colors.primary]

background = "#212121"
foreground = "#34b0d2"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#87d2c3"
cursor = "#0f3754"


# 0x Normal colors

[colors.normal]

black   = "#212121"
red     = "#e1a7bf"
green   = "#80d778"
yellow  = "#c4c9bf"
blue    = "#254a49"
magenta = "#a380d3"
cyan    = "#14ab9c"
white   = "#02c4e0"


# 0x Bright colors

[colors.bright]

black   = "#ffffff"
red     = "#ffccd8"
green   = "#bdffa8"
yellow  = "#d0cbc9"
blue    = "#79afd2"
magenta = "#c4a7d8"
cyan    = "#8bdee0"
white   = "#34b0d2"
