#0x From the SoftServer color palette


# 0x Default colors

[colors.primary]

background = "#242626"
foreground = "#99a3a2"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#d1dfde"
cursor = "#7f8786"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#a16869"
green   = "#99a569"
yellow  = "#a29069"
blue    = "#6a8fa3"
magenta = "#6971a3"
cyan    = "#6ba48f"
white   = "#99a3a2"


# 0x Bright colors

[colors.bright]

black   = "#666c6b"
red     = "#dc5b5f"
green   = "#bfde54"
yellow  = "#deb35f"
blue    = "#62b1df"
magenta = "#5f6ede"
cyan    = "#64e39c"
white   = "#99a3a2"
