#0x From the Solarized_Darcula color palette


# 0x Default colors

[colors.primary]

background = "#3d3f41"
foreground = "#d2d8d9"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#708183"
cursor = "#214283"


# 0x Normal colors

[colors.normal]

black   = "#25292a"
red     = "#f24840"
green   = "#629655"
yellow  = "#b68800"
blue    = "#2074c7"
magenta = "#797fd4"
cyan    = "#15968d"
white   = "#d2d8d9"


# 0x Bright colors

[colors.bright]

black   = "#25292a"
red     = "#f24840"
green   = "#629655"
yellow  = "#b68800"
blue    = "#2074c7"
magenta = "#797fd4"
cyan    = "#15968d"
white   = "#d2d8d9"
