#0x From the Solarized_Dark_Higher_Contrast color palette


# 0x Default colors

[colors.primary]

background = "#001e26"
foreground = "#9bc1c2"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#f34a00"
cursor = "#003747"


# 0x Normal colors

[colors.normal]

black   = "#002731"
red     = "#d01b24"
green   = "#6bbe6c"
yellow  = "#a57705"
blue    = "#2075c7"
magenta = "#c61b6e"
cyan    = "#259185"
white   = "#e9e2cb"


# 0x Bright colors

[colors.bright]

black   = "#006388"
red     = "#f4153b"
green   = "#50ee84"
yellow  = "#b17e28"
blue    = "#178dc7"
magenta = "#e14d8e"
cyan    = "#00b29e"
white   = "#9bc1c2"
