#0x From the Spacedust color palette


# 0x Default colors

[colors.primary]

background = "#0a1e24"
foreground = "#ecefc1"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#708183"
cursor = "#0a385c"


# 0x Normal colors

[colors.normal]

black   = "#6e5246"
red     = "#e35a00"
green   = "#5cab96"
yellow  = "#e3cd7b"
blue    = "#0e548b"
magenta = "#e35a00"
cyan    = "#06afc7"
white   = "#f0f1ce"


# 0x Bright colors

[colors.bright]

black   = "#674c31"
red     = "#ff8a39"
green   = "#adcab8"
yellow  = "#ffc777"
blue    = "#67a0cd"
magenta = "#ff8a39"
cyan    = "#83a6b3"
white   = "#ecefc1"
