#0x From the SpaceGray color palette


# 0x Default colors

[colors.primary]

background = "#20232c"
foreground = "#b2b8c2"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#b2b8c2"
cursor = "#15171e"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#af4b57"
green   = "#87b279"
yellow  = "#e5c078"
blue    = "#7c8fa3"
magenta = "#a37996"
cyan    = "#84a6a4"
white   = "#b2b8c2"


# 0x Bright colors

[colors.bright]

black   = "#000000"
red     = "#af4b57"
green   = "#87b279"
yellow  = "#e5c078"
blue    = "#7c8fa3"
magenta = "#a37996"
cyan    = "#84a6a4"
white   = "#b2b8c2"
