#0x From the SpaceGray_Eighties color palette


# 0x Default colors

[colors.primary]

background = "#212121"
foreground = "#bdb9ae"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#bbbbbb"
cursor = "#262e35"


# 0x Normal colors

[colors.normal]

black   = "#15171c"
red     = "#ec5f67"
green   = "#80a763"
yellow  = "#fdc253"
blue    = "#5485c0"
magenta = "#bf83c0"
cyan    = "#57c2c0"
white   = "#eeece7"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#ff6973"
green   = "#93d393"
yellow  = "#ffd156"
blue    = "#4d83d0"
magenta = "#ff55ff"
cyan    = "#83e8e4"
white   = "#bdb9ae"
