# Name: Splurge
# Author: 

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#4a4b4a"
red = "#d7699a"
green = "#80d468"
yellow = "#d7a169"
blue = "#6985d7"
magenta = "#c86ad4"
cyan = "#6fccd1"
white = "#dbdcdc"

[colors.bright]
black = "#696969"
red = "#f5a2b5"
green = "#a3f2a0"
yellow = "#f5cda2"
blue = "#a2c1f5"
magenta = "#d2a2f5"
cyan = "#a0e9f2"
white = "#fdfdfd"
