#0x From the Sundried color palette


# 0x Default colors

[colors.primary]

background = "#1a1818"
foreground = "#c8c8c8"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#fffefe"
cursor = "#302b2a"


# 0x Normal colors

[colors.normal]

black   = "#302b2a"
red     = "#a6463d"
green   = "#577644"
yellow  = "#9c5f2a"
blue    = "#485a98"
magenta = "#854551"
cyan    = "#9c814e"
white   = "#c8c8c8"


# 0x Bright colors

[colors.bright]

black   = "#4d4d47"
red     = "#aa000c"
green   = "#128c20"
yellow  = "#fc6a20"
blue    = "#7898f7"
magenta = "#fc89a0"
cyan    = "#fad384"
white   = "#c8c8c8"
