#0x From the Symfonic color palette


# 0x Default colors

[colors.primary]

background = "#000000"
foreground = "#ffffff"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#dc322f"
cursor = "#073642"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#dc322f"
green   = "#56db3a"
yellow  = "#ff8400"
blue    = "#0084d4"
magenta = "#b729d9"
cyan    = "#ccccff"
white   = "#ffffff"


# 0x Bright colors

[colors.bright]

black   = "#1b1d21"
red     = "#dc322f"
green   = "#56db3a"
yellow  = "#ff8400"
blue    = "#0084d4"
magenta = "#b729d9"
cyan    = "#ccccff"
white   = "#ffffff"
