#0x From the Thayer_Bright color palette


# 0x Default colors

[colors.primary]

background = "#1b1d1e"
foreground = "#f8f8f8"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#fc971e"
cursor = "#4d4d4d"


# 0x Normal colors

[colors.normal]

black   = "#1b1d1e"
red     = "#f92672"
green   = "#4df740"
yellow  = "#f3fd21"
blue    = "#2656d6"
magenta = "#8c54fe"
cyan    = "#37c8b4"
white   = "#ccccc6"


# 0x Bright colors

[colors.bright]

black   = "#505354"
red     = "#ff5995"
green   = "#b6e354"
yellow  = "#feed6c"
blue    = "#3f78ff"
magenta = "#9e6ffe"
cyan    = "#23ced4"
white   = "#f8f8f8"
