#0x From the The_Hulk color palette


# 0x Default colors

[colors.primary]

background = "#1b1d1e"
foreground = "#b4b4b4"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#15b61a"
cursor = "#4d4f4c"


# 0x Normal colors

[colors.normal]

black   = "#1b1d1e"
red     = "#259d1a"
green   = "#13ce2f"
yellow  = "#62e456"
blue    = "#2424f4"
magenta = "#641e73"
cyan    = "#378ca9"
white   = "#d8d8d0"


# 0x Bright colors

[colors.bright]

black   = "#505354"
red     = "#8dff2a"
green   = "#48ff76"
yellow  = "#3afe15"
blue    = "#4f6a95"
magenta = "#72579d"
cyan    = "#3f85a5"
white   = "#b4b4b4"
