# Name: Trim Yer Beard
# Author: franksn

[colors.primary]
background = "#191716"
foreground = "#DABA8B"

[colors.cursor]
text = "#191716"
cursor = "#DABA8B"

[colors.normal]
black = "#0F0E0D"
red = "#845336"
green = "#57553C"
yellow = "#A17E3E"
blue = "#43454F"
magenta = "#604848"
cyan = "#5C6652"
white = "#A18B62"

[colors.bright]
black = "#383332"
red = "#8C4F4A"
green = "#898471"
yellow = "#C8B491"
blue = "#65788F"
magenta = "#755E4A"
cyan = "#718062"
white = "#BC9D66"
