# Name: Twilight (light)
# Author: Chris Kempson

[colors.primary]
background = "#ffffff"
foreground = "#464b50"

[colors.cursor]
text = "#ffffff"
cursor = "#464b50"

[colors.normal]
black = "#1e1e1e"
red = "#cf6a4c"
green = "#8f9d6a"
yellow = "#f9ee98"
blue = "#7587a6"
magenta = "#9b859d"
cyan = "#afc4db"
white = "#a7a7a7"

[colors.bright]
black = "#5f5a60"
red = "#cf6a4c"
green = "#8f9d6a"
yellow = "#f9ee98"
blue = "#7587a6"
magenta = "#9b859d"
cyan = "#afc4db"
white = "#ffffff"
