#0x From the Urple color palette


# 0x Default colors

[colors.primary]

background = "#1b1b23"
foreground = "#86799a"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#a062ea"
cursor = "#a062ea"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#af425b"
green   = "#37a315"
yellow  = "#ac5b41"
blue    = "#554d9a"
magenta = "#6c3ba1"
cyan    = "#808080"
white   = "#87799c"


# 0x Bright colors

[colors.bright]

black   = "#5c3125"
red     = "#ff6387"
green   = "#28e51f"
yellow  = "#f08061"
blue    = "#8579ed"
magenta = "#a05dee"
cyan    = "#eaeaea"
white   = "#86799a"
