#0x From the VibrantInk color palette


# 0x Default colors

[colors.primary]

background = "#000000"
foreground = "#ffffff"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#ffffff"
cursor = "#b4d5ff"


# 0x Normal colors

[colors.normal]

black   = "#868686"
red     = "#ff6600"
green   = "#ccff04"
yellow  = "#ffcc00"
blue    = "#44b3cc"
magenta = "#9933cc"
cyan    = "#44b3cc"
white   = "#f4f4f4"


# 0x Bright colors

[colors.bright]

black   = "#545454"
red     = "#ff0000"
green   = "#00ff00"
yellow  = "#ffff00"
blue    = "#0000ff"
magenta = "#ff00ff"
cyan    = "#00ffff"
white   = "#ffffff"
