# Name: VisiBone
# Author: 

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#666666"
red = "#cc6666"
green = "#66cc99"
yellow = "#cc9966"
blue = "#6699cc"
magenta = "#cc6699"
cyan = "#66cccc"
white = "#cccccc"

[colors.bright]
black = "#999999"
red = "#ff9999"
green = "#99ffcc"
yellow = "#ffcc99"
blue = "#99ccff"
magenta = "#ff99cc"
cyan = "#99ffff"
white = "#ffffff"
