#0x From the WarmNeon color palette


# 0x Default colors

[colors.primary]

background = "#3f3f3f"
foreground = "#afdab6"


# 0x Colors the cursor will use if `custom_cursor_colors` is true

[colors.cursor]

text = "#2fff24"
cursor = "#b0ad21"


# 0x Normal colors

[colors.normal]

black   = "#000000"
red     = "#e24345"
green   = "#38b139"
yellow  = "#dae145"
blue    = "#4260c5"
magenta = "#f81ffb"
cyan    = "#29bad3"
white   = "#d0b8a3"


# 0x Bright colors

[colors.bright]

black   = "#fdfcfc"
red     = "#e86f71"
green   = "#9bc08f"
yellow  = "#ddd979"
blue    = "#7a90d5"
magenta = "#f674b9"
cyan    = "#5ed1e4"
white   = "#afdab6"
