# Name: X::Erosion
# Author: earsplit

[colors.primary]
background = "#181512"
foreground = "#BEA492"

[colors.cursor]
text = "#181512"
cursor = "#BEA492"

[colors.normal]
black = "#332D29"
red = "#8C644C"
green = "#746C48"
yellow = "#908A66"
blue = "#646A6D"
magenta = "#605655"
cyan = "#4B5C5E"
white = "#504339"

[colors.bright]
black = "#817267"
red = "#9F7155"
green = "#857B52"
yellow = "#9C956E"
blue = "#71777A"
magenta = "#656565"
cyan = "#556D70"
white = "#9A875F"
